apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: nodeapp
  template:
    metadata:
      labels:
        deployment: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: gcr.io/issa-project1/nodeapp:b9f224c51b29e1ba56569f4c96d94b660be59e12
        command: ["/hello",
                  "--port=8080",
                  "--enableRiskyFeature=$(ENABLE_RISKY)"]
        ports:
        - containerPort: 8080
        env:
        - name: ALT_GREETING
          valueFrom:
            configMapKeyRef:
              name: nodeapp
              key: altGreeting
        - name: ENABLE_RISKY
          valueFrom:
            configMapKeyRef:
              name: nodeapp
              key: enableRisky
